### ISSUE TITLE
Add Hibernate 5 support

### ISSUE THREAD

**Issue by vladmihalcea** [epiresdasilva/cte-multi-table-bulk-id-stategy#2]
I tried it on Hibernate 5.x and it doesn't work because the API changed significantly. I have a solution that works just fine and I can send you a PR for it, but you need to add a LICENSE first (e.g. Apache v2, MIT, etc).

To support both Hibernate 4.x and 5.x, I think it's better to have two Maven modules and to make the hibernate-core dependency scoped to `runtime`.

**Comment by epiresdasilva** [comment]
The PR was merged. Thank you.

**Comment by vladmihalcea** [comment]
You're welcome.
