### ISSUE TITLE
Send a PullRequest to Hibernate so we could integrate this into our core

### ISSUE THREAD

**Issue by vladmihalcea** [epiresdasilva/cte-multi-table-bulk-id-stategy#5]
You should send the Hibernate 5 CTE implementation to [Hibernate ORM](https://github.com/hibernate/hibernate-orm/pulls) as a Pull Request so that we use it for fixing This for the [HHH-11262](https://hibernate.atlassian.net/browse/HHH-11262). I'll take the Pull Request and continue it so that we can integrate it upstream.

Make sure that you sign the [CLA](https://cla.jboss.org/) first. 

Thanks.

**Comment by epiresdasilva** [comment]
[Pull request](https://github.com/hibernate/hibernate-orm/pull/1747) merged. Thanks @vladmihalcea.
